@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_reservations_api, "Reservations") {
  Container(c_reservations, "Reservations", "API")
  Container(c_reservations_jobs, "Reservations Jobs", "Background Job")
  Container(c_reservations_nservicebuslistener, "Reservations NServiceBusListener", "Background Job")
}

System_Ext(d_cloud_service_azure_active_directory, "Azure Active Directory", "Azure AD")
System_Ext(d_cloud_service_azure_search, "Azure Search", "Azure Cognitive Search")
SystemDb_Ext(d_database_sql_database, "SQL Database", "System.Data.SqlClient")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "NServiceBus.Transport.AzureServiceBus")

Rel(c_reservations, d_cloud_service_azure_active_directory, "Uses", "Azure AD")
Rel(c_reservations, d_cloud_service_azure_search, "Uses", "Azure Cognitive Search")
Rel(c_reservations_jobs, d_database_sql_database, "Reads from and writes to", "System.Data.SqlClient")
Rel(c_reservations, d_database_sql_database, "Reads from and writes to", "SQL Server")
Rel(c_reservations_jobs, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "NServiceBus.Transport.AzureServiceBus")
Rel(c_reservations, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")

@enduml
