@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apim_endpoints, "Apprentice Feedback") {
  Container(c_admin_api, "Admin", "API")
  Container(c_adminaan_api, "AdminAan", "API")
  Container(c_adminroatp_api, "AdminRoatp", "API")
  Container(c_aodp_api, "Aodp", "API")
  Container(c_aparregister_api, "AparRegister", "API")
  Container(c_apimdeveloper_api, "ApimDeveloper", "API")
  Container(c_apprentice_feedback_api, "Apprentice Feedback", "API")
  Container(c_apprentice_feedback_mockapis, "Apprentice Feedback MockApis", "Component")
  Container(c_apprenticeaan_api, "ApprenticeAan", "API")
  Container(c_apprenticeapp, "ApprenticeApp", "API")
  Container(c_apprenticecommitments, "ApprenticeCommitments", "API")
  Container(c_apprenticeportal_api, "ApprenticePortal", "API")
  Container(c_apprenticeportal_mockapis, "ApprenticePortal Mock APIs", "Component")
  Container(c_apprenticeships_api, "Apprenticeships", "API")
  Container(c_apprenticeships_manage, "Apprenticeships Manage", "API")
  Container(c_apprenticeships_stubs, "Apprenticeships Stubs", "Component")
  Container(c_approvals, "Approvals", "API")
  Container(c_approvals_fakeapis, "Approvals FakeApis", "Background Job")
  Container(c_assessors_api, "Assessors", "API")
  Container(c_campaign_api, "Campaign", "API")
  Container(c_digitalcertificates_api, "DigitalCertificates", "API")
  Container(c_digitalcertificates_mockapis, "DigitalCertificates MockAPIs", "Component")
  Container(c_earnings_api, "Earnings", "API")
  Container(c_employer_aan_api, "Employer Aan", "API")
  Container(c_employer_accounts_api, "Employer Accounts Api", "API")
  Container(c_employer_finance_api, "EmployerFinance", "API")
  Container(c_employer_incentives_api, "EmployerFinance Incentives", "API")
  Container(c_employercontactforms_api, "EmployerContactForms", "API")
  Container(c_employerfeedback_api, "EmployerFeedback API", "API")
  Container(c_employerpr, "EmployerPR", "API")
}

SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
SystemDb_Ext(d_cache_stackexchange_redis, "StackExchange Redis", "Redis")
System_Ext(d_cloud_service_application_insights, "Application Insights", "Azure Application Insights")
System_Ext(d_cloud_service_azure_active_directory, "Azure Active Directory", "Azure Active Directory")
System_Ext(d_cloud_service_azure_application_insights, "Azure Application Insights")
System_Ext(d_cloud_service_azure_key_vault, "Azure Key Vault")
System_Ext(d_http_api_aan_hub, "Aan Hub", "RestEase")
System_Ext(d_http_api_aan_hub_api, "Aan Hub API", "RestEase")
System_Ext(d_http_api_accounts, "Accounts")
System_Ext(d_http_api_accounts_api, "Accounts API", "HttpClient")
System_Ext(d_http_api_apim_developer_api, "Apim Developer API", "HttpClient")
System_Ext(d_http_api_apply_api, "Apply API")
System_Ext(d_http_api_apprentice_accounts, "Apprentice Accounts")
System_Ext(d_http_api_apprentice_accounts_api, "Apprentice Accounts API", "HttpClient")
System_Ext(d_http_api_apprentice_feedback_api, "Apprentice Feedback API", "HttpClient")
System_Ext(d_http_api_apprentice_login, "Apprentice Login")
System_Ext(d_http_api_assessor_mock_api, "Assessor Mock API", "WireMock.Net")
System_Ext(d_http_api_assessors, "Assessors")
System_Ext(d_http_api_assessors_api, "Assessors API", "HttpClient")
System_Ext(d_http_api_collection_calendar, "Collection Calendar", "HttpClient")
System_Ext(d_http_api_collection_calendar_api, "Collection Calendar API", "HttpClient")
System_Ext(d_http_api_commitments, "Commitments", "HttpClient")
System_Ext(d_http_api_commitments_v2, "Commitments V2")
System_Ext(d_http_api_contentful, "Contentful")
System_Ext(d_http_api_courses, "Courses")
System_Ext(d_http_api_courses_api, "Courses API", "RestEase")
System_Ext(d_http_api_customer_engagement_finance, "Customer Engagement Finance", "HttpClient")
System_Ext(d_http_api_dfe_sign_in, "Dfe Sign In", "HttpClient")
System_Ext(d_http_api_digital_certificates, "Digital Certificates")
System_Ext(d_http_api_digital_certificates_api, "Digital Certificates API", "HttpClient")
System_Ext(d_http_api_earnings_api, "Earnings API", "HttpClient")
System_Ext(d_http_api_employer_feedback, "Employer Feedback")
System_Ext(d_http_api_employer_incentives, "Employer Incentives", "HttpClient")
System_Ext(d_http_api_employer_profiles, "Employer Profiles", "RestEase")
System_Ext(d_http_api_finance_api, "Finance API", "HttpClient")
System_Ext(d_http_api_find_apprenticeship, "Find Apprenticeship", "HttpClient")
System_Ext(d_http_api_learning, "Learning", "HttpClient")
System_Ext(d_http_api_learning_api, "Learning API", "HttpClient")
System_Ext(d_http_api_location, "Location", "HttpClient")
System_Ext(d_http_api_location_api, "Location API", "HttpClient")
System_Ext(d_http_api_pensions_regulator, "Pensions Regulator", "RestEase")
System_Ext(d_http_api_provider_courses, "Provider Courses", "HttpClient")
System_Ext(d_http_api_provider_relationships, "Provider Relationships", "RestEase")
System_Ext(d_http_api_roatp_service, "Roatp Service", "RestEase")
System_Ext(d_http_api_roatp_v2_course_management, "ROATP V2 Course Management", "RestEase")
System_Ext(d_http_api_training_provider, "Training Provider")

Rel(c_apprenticeapp, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_approvals, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_campaign_api, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_adminaan_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_aodp_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_aparregister_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_apprenticeapp, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employerfeedback_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employer_aan_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employer_accounts_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_apprenticeportal_api, d_cache_stackexchange_redis, "Caches data in", "Redis")
Rel(c_apprenticeportal_api, d_cloud_service_application_insights, "Uses", "Azure Application Insights")
Rel(c_apprenticeportal_api, d_cloud_service_azure_active_directory, "Uses", "Azure Active Directory")
Rel(c_apprenticeapp, d_cloud_service_azure_application_insights, "Uses")
Rel(c_aodp_api, d_cloud_service_azure_key_vault, "Uses")
Rel(c_aparregister_api, d_cloud_service_azure_key_vault, "Uses")
Rel(c_adminaan_api, d_http_api_aan_hub, "Calls the API of", "RestEase")
Rel(c_employer_aan_api, d_http_api_aan_hub, "Calls the API of", "RestEase HTTP client")
Rel(c_apprenticeaan_api, d_http_api_aan_hub_api, "Calls the API of", "RestEase")
Rel(c_employerfeedback_api, d_http_api_accounts, "Calls the API of")
Rel(c_employerpr, d_http_api_accounts, "Calls the API of", "RestEase")
Rel(c_employer_finance_api, d_http_api_accounts, "Calls the API of", "HttpClient")
Rel(c_apimdeveloper_api, d_http_api_accounts_api, "Calls the API of", "HttpClient")
Rel(c_apimdeveloper_api, d_http_api_apim_developer_api, "Calls the API of", "HttpClient")
Rel(c_adminroatp_api, d_http_api_apply_api, "Calls the API of")
Rel(c_apprenticecommitments, d_http_api_apprentice_accounts, "Calls the API of")
Rel(c_employer_aan_api, d_http_api_apprentice_accounts, "Calls the API of", "RestEase HTTP client")
Rel(c_apprentice_feedback_api, d_http_api_apprentice_accounts_api, "Calls the API of", "HttpClient")
Rel(c_apprentice_feedback_api, d_http_api_apprentice_feedback_api, "Calls the API of", "HttpClient")
Rel(c_apprenticecommitments, d_http_api_apprentice_login, "Calls the API of")
Rel(c_apprentice_feedback_mockapis, d_http_api_assessor_mock_api, "Calls the API of", "WireMock.Net")
Rel(c_admin_api, d_http_api_assessors, "Calls the API of")
Rel(c_apprentice_feedback_api, d_http_api_assessors_api, "Calls the API of", "HttpClient")
Rel(c_digitalcertificates_api, d_http_api_assessors_api, "Calls the API of", "HttpClient")
Rel(c_apprenticeships_manage, d_http_api_collection_calendar, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_collection_calendar_api, "Calls the API of", "HttpClient")
Rel(c_employer_incentives_api, d_http_api_commitments, "Calls the API of", "HttpClient")
Rel(c_apprenticecommitments, d_http_api_commitments_v2, "Calls the API of")
Rel(c_approvals, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_assessors_api, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employerfeedback_api, d_http_api_commitments_v2, "Calls the API of")
Rel(c_employer_aan_api, d_http_api_commitments_v2, "Calls the API of", "RestEase HTTP client")
Rel(c_employer_accounts_api, d_http_api_commitments_v2, "Calls the API of")
Rel(c_apprenticeapp, d_http_api_contentful, "Calls the API of")
Rel(c_apprenticecommitments, d_http_api_courses, "Calls the API of")
Rel(c_approvals, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_assessors_api, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_employer_aan_api, d_http_api_courses, "Calls the API of", "RestEase HTTP client")
Rel(c_apprenticeaan_api, d_http_api_courses_api, "Calls the API of", "RestEase")
Rel(c_earnings_api, d_http_api_courses_api, "Calls the API of", "HttpClient")
Rel(c_employer_finance_api, d_http_api_courses_api, "Calls the API of", "HttpClient")
Rel(c_employer_incentives_api, d_http_api_customer_engagement_finance, "Calls the API of", "HttpClient")
Rel(c_aodp_api, d_http_api_dfe_sign_in, "Calls the API of", "HttpClient")
Rel(c_admin_api, d_http_api_digital_certificates, "Calls the API of")
Rel(c_digitalcertificates_api, d_http_api_digital_certificates_api, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_earnings_api, "Calls the API of", "HttpClient")
Rel(c_employerfeedback_api, d_http_api_employer_feedback, "Calls the API of")
Rel(c_employer_incentives_api, d_http_api_employer_incentives, "Calls the API of", "HttpClient")
Rel(c_employerpr, d_http_api_employer_profiles, "Calls the API of", "RestEase")
Rel(c_employer_finance_api, d_http_api_finance_api, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_find_apprenticeship, "Calls the API of", "HttpClient")
Rel(c_apprenticeships_manage, d_http_api_learning, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_learning_api, "Calls the API of", "HttpClient")
Rel(c_assessors_api, d_http_api_location, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_location, "Calls the API of", "HttpClient")
Rel(c_employercontactforms_api, d_http_api_location, "Calls the API of")
Rel(c_digitalcertificates_api, d_http_api_location_api, "Calls the API of", "HttpClient")
Rel(c_employerpr, d_http_api_pensions_regulator, "Calls the API of", "RestEase")
Rel(c_approvals, d_http_api_provider_courses, "Calls the API of", "HttpClient")
Rel(c_employerpr, d_http_api_provider_relationships, "Calls the API of", "RestEase")
Rel(c_adminroatp_api, d_http_api_roatp_service, "Calls the API of", "RestEase")
Rel(c_aparregister_api, d_http_api_roatp_service, "Calls the API of", "HttpClient")
Rel(c_employerpr, d_http_api_roatp_v2_course_management, "Calls the API of", "RestEase")
Rel(c_apprenticecommitments, d_http_api_training_provider, "Calls the API of")

@enduml
