@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apim_endpoints, "Apprentice Portal") {
  Container(c_aodp_api, "Aodp", "API")
  Container(c_apar_register_api, "Apar Register", "API")
  Container(c_apimdeveloper_api, "ApimDeveloper", "API")
  Container(c_apprentice_commitments, "Apprentice Commitments", "API")
  Container(c_apprentice_commitments_mockapis, "Apprentice Commitments MockApis", "Component")
  Container(c_apprentice_feedback_api, "Apprentice Feedback", "API")
  Container(c_apprentice_feedback_mockapis, "Apprentice Feedback MockApis", "Component")
  Container(c_apprentice_portal, "Apprentice Portal", "API")
  Container(c_apprentice_portal_mock_apis, "Apprentice Portal Mock APIs", "Component")
  Container(c_apprenticeaan_api, "ApprenticeAan", "API")
  Container(c_apprenticeapp_api, "ApprenticeApp", "API")
  Container(c_apprenticeships, "Apprenticeships", "API")
  Container(c_apprenticeships_stubs, "Apprenticeships Stubs", "Component")
  Container(c_apprenticeshipsmanage, "ApprenticeshipsManage", "API")
  Container(c_approvals, "Approvals", "API")
  Container(c_assessors_api, "Assessors", "API")
  Container(c_campaign_api, "Campaign", "API")
  Container(c_digital_certificates_api, "Digital Certificates", "API")
  Container(c_digital_certificates_mockapis, "Digital Certificates Mock Apis", "Component")
  Container(c_earnings_api, "Earnings", "API")
  Container(c_employer_aan_api, "EmployerAan", "API")
  Container(c_employer_accounts_api, "Employer Accounts", "API")
  Container(c_employer_finance_api, "SFA.DAS.EmployerFinance", "API")
  Container(c_employer_incentives_api, "SFA.DAS.EmployerIncentives", "API")
  Container(c_employer_incentives_fake_inner_apis, "SFA.DAS.EmployerIncentives FakeInnerApis", "Component")
  Container(c_employercontactforms, "EmployerContactForms", "API")
  Container(c_employerfeedback, "EmployerFeedback", "API")
  Container(c_employerpr_api, "EmployerPR", "API")
  Container(c_sfa_das_admin_api, "SFA.DAS.Admin", "API")
  Container(c_sfa_das_adminaan_api, "SFA.DAS.AdminAan", "API")
  Container(c_sfa_das_adminroatp_api, "SFA.DAS.AdminRoatp", "API")
}

SystemDb_Ext(d_cache_apim_endpoints_redis, "Apim Endpoints Redis", "Redis")
SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "redis")
System_Ext(d_cloud_service_application_insights, "Application Insights")
System_Ext(d_cloud_service_azure_application_insights, "Azure Application Insights", "Azure Application Insights")
System_Ext(d_http_api_aan_hub, "Aan Hub", "RestEase")
System_Ext(d_http_api_accounts, "Accounts", "HttpClient")
System_Ext(d_http_api_accounts_api, "Accounts API", "HttpClient")
System_Ext(d_http_api_accounts_inner, "Accounts Inner", "HTTP")
System_Ext(d_http_api_aodp_outer_api, "Aodp Outer API", "HttpClient")
System_Ext(d_http_api_apply_api, "Apply API", "HttpClient")
System_Ext(d_http_api_apprentice_accounts, "Apprentice Accounts", "HttpClient")
System_Ext(d_http_api_apprentice_commitments, "Apprentice Commitments", "HttpClient")
System_Ext(d_http_api_apprentice_feedback, "Apprentice Feedback", "HttpClient")
System_Ext(d_http_api_apprentice_progress, "Apprentice Progress", "HttpClient")
System_Ext(d_http_api_assessor_inner, "Assessor Inner", "WireMock")
System_Ext(d_http_api_assessors, "Assessors", "HttpClient")
System_Ext(d_http_api_assessors_api, "Assessors API")
System_Ext(d_http_api_collection_calendar, "Collection Calendar", "HttpClient")
System_Ext(d_http_api_collection_calendar_api, "Collection Calendar API")
System_Ext(d_http_api_commitments, "Commitments", "HttpClient")
System_Ext(d_http_api_commitments_v2, "Commitments V2")
System_Ext(d_http_api_commitments_v2_api, "Commitments V2 API", "HttpClient")
System_Ext(d_http_api_companies_house, "Companies House", "HTTP")
System_Ext(d_http_api_contentful, "Contentful", "contentful.csharp")
System_Ext(d_http_api_contentful_master, "Contentful Master", "HttpClient")
System_Ext(d_http_api_contentful_preview, "Contentful Preview", "HttpClient")
System_Ext(d_http_api_courses, "Courses", "HttpClient")
System_Ext(d_http_api_courses_api, "Courses API")
System_Ext(d_http_api_customer_engagement_api, "Customer Engagement API", "WireMock")
System_Ext(d_http_api_dfe_sign_in, "Dfe Sign In", "HttpClient")
System_Ext(d_http_api_digital_certificates, "Digital Certificates", "HttpClient")
System_Ext(d_http_api_digital_certificates_api, "Digital Certificates API")
System_Ext(d_http_api_earnings_api, "Earnings API")
System_Ext(d_http_api_employer_profiles, "Employer Profiles", "HttpClient")
System_Ext(d_http_api_finance, "Finance", "HTTP")
System_Ext(d_http_api_find_apprenticeship, "Find Apprenticeship", "HttpClient")
System_Ext(d_http_api_internal_api, "Internal API", "HttpClient")
System_Ext(d_http_api_learning, "Learning", "HttpClient")
System_Ext(d_http_api_learning_api, "Learning API")
System_Ext(d_http_api_levy_transfer_matching, "Levy Transfer Matching", "HttpClient")
System_Ext(d_http_api_location, "Location", "HTTP")
System_Ext(d_http_api_location_api, "Location API", "RestEase")
System_Ext(d_http_api_pension_regulator, "Pension Regulator", "HTTP")
System_Ext(d_http_api_provider_payment_events, "Provider Payment Events", "HttpClient")
System_Ext(d_http_api_provider_relationships, "Provider Relationships", "HTTP")
System_Ext(d_http_api_public_sector_organisation, "Public Sector Organisation", "HTTP")
System_Ext(d_http_api_reservation, "Reservation", "HTTP")
System_Ext(d_http_api_roatp_course_management, "RoATP Course Management", "HttpClient")
System_Ext(d_http_api_roatp_service, "Roatp Service", "HttpClient")

Rel(c_employer_aan_api, d_cache_apim_endpoints_redis, "Caches data in", "Redis")
Rel(c_employer_accounts_api, d_cache_apim_endpoints_redis, "Caches data in", "Redis")
Rel(c_apprenticeapp_api, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_apprentice_commitments, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_apprentice_portal, d_cache_redis_cache, "Caches data in", "redis")
Rel(c_aodp_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_apar_register_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_apimdeveloper_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_apprenticeaan_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_apprenticeapp_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_sfa_das_adminaan_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employercontactforms, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employerfeedback, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_employer_finance_api, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_assessors_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_campaign_api, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_apprenticeships, d_cloud_service_application_insights, "Uses")
Rel(c_apprentice_portal, d_cloud_service_application_insights, "Uses")
Rel(c_employerpr_api, d_cloud_service_azure_application_insights, "Uses", "Azure Application Insights")
Rel(c_apprenticeaan_api, d_http_api_aan_hub, "Calls the API of", "RestEase")
Rel(c_sfa_das_adminaan_api, d_http_api_aan_hub, "Calls the API of", "RestEase")
Rel(c_employer_aan_api, d_http_api_aan_hub, "Calls the API of", "HTTP")
Rel(c_apimdeveloper_api, d_http_api_accounts, "Calls the API of", "HttpClient")
Rel(c_employerpr_api, d_http_api_accounts, "Calls the API of", "HTTP")
Rel(c_employer_finance_api, d_http_api_accounts, "Calls the API of", "HttpClient")
Rel(c_employerfeedback, d_http_api_accounts_api, "Calls the API of", "HttpClient")
Rel(c_employer_aan_api, d_http_api_accounts_inner, "Calls the API of", "HTTP")
Rel(c_aodp_api, d_http_api_aodp_outer_api, "Calls the API of", "HttpClient")
Rel(c_sfa_das_adminroatp_api, d_http_api_apply_api, "Calls the API of", "HttpClient")
Rel(c_apprentice_commitments, d_http_api_apprentice_accounts, "Calls the API of", "HttpClient")
Rel(c_apprentice_feedback_api, d_http_api_apprentice_accounts, "Calls the API of", "HttpClient")
Rel(c_employer_aan_api, d_http_api_apprentice_accounts, "Calls the API of", "HTTP")
Rel(c_apprentice_feedback_api, d_http_api_apprentice_commitments, "Calls the API of", "HttpClient")
Rel(c_apprentice_feedback_api, d_http_api_apprentice_feedback, "Calls the API of", "HttpClient")
Rel(c_apprenticeapp_api, d_http_api_apprentice_progress, "Calls the API of", "HttpClient")
Rel(c_apprentice_commitments_mockapis, d_http_api_assessor_inner, "Calls the API of", "WireMock")
Rel(c_sfa_das_admin_api, d_http_api_assessors, "Calls the API of", "HttpClient")
Rel(c_apprentice_feedback_api, d_http_api_assessors, "Calls the API of", "HttpClient")
Rel(c_digital_certificates_api, d_http_api_assessors_api, "Calls the API of")
Rel(c_apprenticeshipsmanage, d_http_api_collection_calendar, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_collection_calendar_api, "Calls the API of")
Rel(c_approvals, d_http_api_commitments, "Calls the API of", "HttpClient")
Rel(c_employer_incentives_api, d_http_api_commitments, "Calls the API of", "HttpClient")
Rel(c_apprentice_commitments, d_http_api_commitments_v2, "Calls the API of")
Rel(c_employer_aan_api, d_http_api_commitments_v2, "Calls the API of", "HTTP")
Rel(c_assessors_api, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employerfeedback, d_http_api_commitments_v2_api, "Calls the API of", "HttpClient")
Rel(c_employer_accounts_api, d_http_api_companies_house, "Calls the API of", "HTTP")
Rel(c_apprenticeapp_api, d_http_api_contentful, "Calls the API of", "contentful.csharp")
Rel(c_campaign_api, d_http_api_contentful_master, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_contentful_preview, "Calls the API of", "HttpClient")
Rel(c_approvals, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_apprentice_commitments, d_http_api_courses, "Calls the API of")
Rel(c_employer_aan_api, d_http_api_courses, "Calls the API of", "HTTP")
Rel(c_assessors_api, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_courses, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_courses_api, "Calls the API of")
Rel(c_employer_incentives_fake_inner_apis, d_http_api_customer_engagement_api, "Calls the API of", "WireMock")
Rel(c_aodp_api, d_http_api_dfe_sign_in, "Calls the API of", "HttpClient")
Rel(c_sfa_das_admin_api, d_http_api_digital_certificates, "Calls the API of", "HttpClient")
Rel(c_digital_certificates_api, d_http_api_digital_certificates_api, "Calls the API of")
Rel(c_earnings_api, d_http_api_earnings_api, "Calls the API of")
Rel(c_approvals, d_http_api_employer_profiles, "Calls the API of", "HttpClient")
Rel(c_apimdeveloper_api, d_http_api_employer_profiles, "Calls the API of", "HttpClient")
Rel(c_employerpr_api, d_http_api_employer_profiles, "Calls the API of", "HTTP")
Rel(c_employer_aan_api, d_http_api_employer_profiles, "Calls the API of", "HTTP")
Rel(c_employer_accounts_api, d_http_api_finance, "Calls the API of", "HTTP")
Rel(c_campaign_api, d_http_api_find_apprenticeship, "Calls the API of", "HttpClient")
Rel(c_employercontactforms, d_http_api_internal_api, "Calls the API of", "HttpClient")
Rel(c_apprenticeshipsmanage, d_http_api_learning, "Calls the API of", "HttpClient")
Rel(c_earnings_api, d_http_api_learning_api, "Calls the API of")
Rel(c_employer_finance_api, d_http_api_levy_transfer_matching, "Calls the API of", "HttpClient")
Rel(c_employer_aan_api, d_http_api_location, "Calls the API of", "HTTP")
Rel(c_assessors_api, d_http_api_location, "Calls the API of", "HttpClient")
Rel(c_campaign_api, d_http_api_location, "Calls the API of", "HttpClient")
Rel(c_sfa_das_adminaan_api, d_http_api_location_api, "Calls the API of", "RestEase")
Rel(c_digital_certificates_api, d_http_api_location_api, "Calls the API of")
Rel(c_employercontactforms, d_http_api_location_api, "Calls the API of", "HttpClient")
Rel(c_employerpr_api, d_http_api_pension_regulator, "Calls the API of", "HTTP")
Rel(c_approvals, d_http_api_provider_payment_events, "Calls the API of", "HttpClient")
Rel(c_employerpr_api, d_http_api_provider_relationships, "Calls the API of", "HTTP")
Rel(c_employer_accounts_api, d_http_api_public_sector_organisation, "Calls the API of", "HTTP")
Rel(c_employer_accounts_api, d_http_api_reservation, "Calls the API of", "HTTP")
Rel(c_sfa_das_adminroatp_api, d_http_api_roatp_course_management, "Calls the API of", "HttpClient")
Rel(c_employerpr_api, d_http_api_roatp_course_management, "Calls the API of", "HTTP")
Rel(c_apar_register_api, d_http_api_roatp_service, "Calls the API of", "HttpClient")
Rel(c_sfa_das_adminroatp_api, d_http_api_roatp_service, "Calls the API of", "RestEase")

@enduml
