@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_learning, "Learning") {
  Container(c_learning, "Learning", "API")
  Container(c_learning_command, "Learning Command", "Background Job")
  Container(c_learning_jobs, "Learning Jobs", "Background Job")
  Container(c_learning_testmessagepublisher, "Learning TestMessagePublisher", "Component")
  Container(c_testhelpers, "TestHelpers", "Component")
}

System_Ext(d_cloud_service_azure_table_storage, "Azure Table Storage", "Azure Table Storage")
SystemDb_Ext(d_database_learning_database, "Learning Database", "Microsoft.EntityFrameworkCore.SqlServer")
System_Ext(d_http_api_learning_outer, "Learning Outer", "HttpClient")
SystemQueue_Ext(d_message_broker_azure_storage_queues, "Azure Storage Queues", "Azure Storage Queues")
SystemQueue_Ext(d_message_broker_nservicebus, "NServiceBus", "NServiceBus")

Rel(c_learning, d_cloud_service_azure_table_storage, "Uses", "Azure Table Storage")
Rel(c_learning_jobs, d_cloud_service_azure_table_storage, "Uses", "Azure Table Storage")
Rel(c_learning_command, d_database_learning_database, "Reads from and writes to", "Microsoft.EntityFrameworkCore.SqlServer")
Rel(c_learning, d_database_learning_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_testhelpers, d_database_learning_database, "Reads from and writes to")
Rel(c_learning_jobs, d_database_learning_database, "Reads from and writes to", "Entity Framework")
Rel(c_learning_command, d_http_api_learning_outer, "Calls the API of", "HttpClient")
Rel(c_learning_jobs, d_message_broker_azure_storage_queues, "Publishes messages to and consumes messages from", "Azure Storage Queues")
Rel(c_learning_testmessagepublisher, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_learning, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_learning_jobs, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")

@enduml
