@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_findapprenticeship_api, "FindApprenticeships") {
  Container(c_findapprenticeships, "FindApprenticeships", "API")
}

SystemDb_Ext(d_database_sql_server, "SQL Server", "Entity Framework Core")

Rel(c_findapprenticeships, d_database_sql_server, "Reads from and writes to", "Entity Framework Core")

@enduml
