@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apprentice_commitments_api, "Apprentice Commitments") {
  Container(c_apprentice_commitments, "Apprentice Commitments", "API")
}

System_Ext(d_cloud_service_azure_table_storage, "Azure Table Storage", "Azure Table Storage")
SystemDb_Ext(d_database_sql_server, "SQL Server", "Microsoft SQL Server")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "Azure Service Bus")

Rel(c_apprentice_commitments, d_cloud_service_azure_table_storage, "Uses", "Azure Table Storage")
Rel(c_apprentice_commitments, d_database_sql_server, "Reads from and writes to", "Microsoft SQL Server")
Rel(c_apprentice_commitments, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")

@enduml
