@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apprentice_progress_api, "Apprentice Progress") {
  Container(c_apprentice_progress, "Apprentice Progress", "API")
  Container(c_apprentice_progress_functions, "Apprentice Progress Functions", "Background Job")
}

SystemDb_Ext(d_database_apprentice_progress_database, "Apprentice Progress Database", "SQL Server")
System_Ext(d_http_api_apprentice_progress_api, "Apprentice Progress API", "HTTP")

Rel(c_apprentice_progress, d_database_apprentice_progress_database, "Reads from and writes to", "SQL Server")
Rel(c_apprentice_progress_functions, d_http_api_apprentice_progress_api, "Calls the API of", "HTTP")

@enduml
