@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_payments_v2_datalocks, "Payments DataLocks") {
  Container(c_payments_approvals_service, "Payments Approvals Service", "Background Job")
  Container(c_payments_datalock_event_service, "Payments Datalock Event Service", "Background Job")
  Container(c_payments_datalock_proxy_service, "Payments Datalock Proxy Service", "Background Job")
  Container(c_payments_datalock_service, "Payments Datalock Service", "Background Job")
  Container(c_payments_datalock_status_changed_service, "Payments Datalock Status Changed Service", "Background Job")
  Container(c_payments_datalocks_domain, "Payments DataLocks Domain", "Component")
  Container(c_payments_datalocks_messages, "Payments DataLocks Messages", "Component")
  Container(c_payments_datalocks_messages_internal, "Payments DataLocks Messages Internal", "Component")
  Container(c_payments_datalocks_model, "Payments DataLocks Model", "Component")
}

@enduml
