@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_campaign_api, "Campaign") {
  Container(c_campaign, "Campaign", "API")
}

SystemDb_Ext(d_database_azure_sql_database, "Azure SQL Database", "Microsoft SQL Server")

Rel(c_campaign, d_database_azure_sql_database, "Reads from and writes to", "Microsoft SQL Server")

@enduml
