@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_campaign_api, "Campaign") {
  Container(c_campaign, "Campaign", "API")
}

System_Ext(d_cloud_service_azure_managed_identity, "Azure Managed Identity", "Azure.Identity")
SystemDb_Ext(d_database_campaign_sql_database, "Campaign SQL Database", "Microsoft.Data.SqlClient")

Rel(c_campaign, d_cloud_service_azure_managed_identity, "Uses", "Azure.Identity")
Rel(c_campaign, d_database_campaign_sql_database, "Reads from and writes to", "Microsoft.Data.SqlClient")

@enduml
