@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_employer_feedback_api, "Employer Feedback") {
  Container(c_employer_feedback_api, "Employer Feedback", "API")
}

System_Ext(d_cloud_service_azure_app_configuration, "Azure App Configuration", "Azure Table Storage")
System_Ext(d_cloud_service_azure_application_insights, "Azure Application Insights", "Azure Application Insights")
SystemDb_Ext(d_database_employer_feedback_database, "Employer Feedback Database", "Microsoft SQL Server")

Rel(c_employer_feedback_api, d_cloud_service_azure_app_configuration, "Uses", "Azure Table Storage")
Rel(c_employer_feedback_api, d_cloud_service_azure_application_insights, "Uses", "Azure Application Insights")
Rel(c_employer_feedback_api, d_database_employer_feedback_database, "Reads from and writes to", "Microsoft SQL Server")

@enduml
