@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_admin_roatp_web, "Admin Roatp") {
  Container(c_admin_roatp, "Admin Roatp", "Web Application")
}

SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
System_Ext(d_http_api_outer_api, "Outer API", "HTTP/REST")

Rel(c_admin_roatp, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_admin_roatp, d_http_api_outer_api, "Calls the API of", "HTTP/REST")

@enduml
