@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_employer_finance, "Employer Finance") {
  Container(c_employer_finance, "Employer Finance", "Component")
  Container(c_employer_finance_2, "Employer Finance", "API")
  Container(c_employerfinance_jobs, "EmployerFinance Jobs", "Background Job")
  Container(c_employerfinance_messagehandlers, "EmployerFinance MessageHandlers", "Background Job")
  Container(c_employerfinance_web, "EmployerFinance Web", "Web Application")
}

SystemDb_Ext(d_cache_redis, "Redis", "Microsoft.AspNetCore.DataProtection.StackExchangeRedis")
System_Ext(d_cloud_service_azure_key_vault, "Azure Key Vault", "Azure.Identity")
SystemDb_Ext(d_database_sql_server, "SQL Server", "System.Data.SqlClient")
System_Ext(d_http_api_apprenticeship_levy, "Apprenticeship Levy", "HttpClient")
System_Ext(d_http_api_commitments_v2, "Commitments V2", "HttpClient")
System_Ext(d_http_api_content_api, "Content API", "HttpClient")
System_Ext(d_http_api_employer_finance_authentication, "Employer Finance Authentication", "HttpClient")
System_Ext(d_http_api_outer_api, "Outer API", "HttpClient")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "Azure.Messaging.ServiceBus")

Rel(c_employer_finance, d_cache_redis, "Caches data in", "Microsoft.AspNetCore.DataProtection.StackExchangeRedis")
Rel(c_employer_finance_2, d_cache_redis, "Caches data in", "Redis")
Rel(c_employer_finance, d_cloud_service_azure_key_vault, "Uses", "Azure.Identity")
Rel(c_employer_finance, d_database_sql_server, "Reads from and writes to", "System.Data.SqlClient")
Rel(c_employer_finance_2, d_database_sql_server, "Reads from and writes to", "SqlServer")
Rel(c_employerfinance_messagehandlers, d_database_sql_server, "Reads from and writes to", "SQL Server")
Rel(c_employerfinance_web, d_database_sql_server, "Reads from and writes to", "SQL Server")
Rel(c_employerfinance_messagehandlers, d_http_api_apprenticeship_levy, "Calls the API of", "HttpClient")
Rel(c_employerfinance_messagehandlers, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employerfinance_web, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employer_finance_2, d_http_api_content_api, "Calls the API of", "HttpClient")
Rel(c_employer_finance_2, d_http_api_employer_finance_authentication, "Calls the API of", "HttpClient")
Rel(c_employer_finance_2, d_http_api_outer_api, "Calls the API of", "HttpClient")
Rel(c_employerfinance_web, d_http_api_outer_api, "Calls the API of", "HttpClient")
Rel(c_employer_finance, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure.Messaging.ServiceBus")
Rel(c_employerfinance_messagehandlers, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")

@enduml
