@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_courses_api, "Courses") {
  Container(c_courses, "Courses", "API")
}

SystemDb_Ext(d_cache_sfa_das_courses_redis_cache, "SFA DAS Courses Redis Cache", "StackExchange.Redis")
System_Ext(d_cloud_service_azure_identity, "Azure Identity", "Azure SDK")
SystemDb_Ext(d_database_sfa_das_courses_database, "SFA DAS Courses Database", "Entity Framework Core")
System_Ext(d_http_api_data_download, "Data Download", "HttpClient")
System_Ext(d_http_api_qualification_sector_subject_area, "Qualification Sector Subject Area", "HttpClient")
System_Ext(d_http_api_skills_england, "Skills England", "HttpClient")
System_Ext(d_http_api_slack_notification, "Slack Notification", "HttpClient")

Rel(c_courses, d_cache_sfa_das_courses_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_courses, d_cloud_service_azure_identity, "Uses", "Azure SDK")
Rel(c_courses, d_database_sfa_das_courses_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_courses, d_http_api_data_download, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_qualification_sector_subject_area, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_skills_england, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_slack_notification, "Calls the API of", "HttpClient")

@enduml
