@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_courses_api, "Courses") {
  Container(c_courses, "Courses", "API")
}

SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
SystemDb_Ext(d_database_courses_database, "Courses Database", "Entity Framework Core")
System_Ext(d_http_api_data_download, "Data Download", "HttpClient")
System_Ext(d_http_api_qualification_sector_subject_area, "Qualification Sector Subject Area", "HttpClient")
System_Ext(d_http_api_skills_england, "Skills England", "HttpClient")
System_Ext(d_http_api_slack_notification, "Slack Notification", "HttpClient")

Rel(c_courses, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_courses, d_database_courses_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_courses, d_http_api_data_download, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_qualification_sector_subject_area, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_skills_england, "Calls the API of", "HttpClient")
Rel(c_courses, d_http_api_slack_notification, "Calls the API of", "HttpClient")

@enduml
