@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apprentice_portal_web, "Apprentice Portal") {
  Container(c_apprentice_portal_web, "Apprentice Portal", "Web Application")
}

SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
System_Ext(d_cloud_service_azure_table_storage_configuration, "Azure Table Storage Configuration", "Azure Table Storage")

Rel(c_apprentice_portal_web, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_apprentice_portal_web, d_cloud_service_azure_table_storage_configuration, "Uses", "Azure Table Storage")

@enduml
