@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_apprentice_feedback_api, "Apprentice Feedback") {
  Container(c_apprentice_feedback, "Apprentice Feedback", "API")
}

System_Ext(d_cloud_service_azure_table_storage, "Azure Table Storage", "Azure Table Storage")
SystemDb_Ext(d_database_apprentice_feedback_database, "Apprentice Feedback Database", "SQL Server")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "Azure Service Bus")

Rel(c_apprentice_feedback, d_cloud_service_azure_table_storage, "Uses", "Azure Table Storage")
Rel(c_apprentice_feedback, d_database_apprentice_feedback_database, "Reads from and writes to", "SQL Server")
Rel(c_apprentice_feedback, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")

@enduml
