@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_employercommitments_v2, "Employer Commitments") {
  Container(c_employer_commitments, "Employer Commitments", "Web Application")
}

SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
System_Ext(d_http_api_approvals_api, "Approvals API", "HttpClient")
System_Ext(d_http_api_commitment_permissions_api, "Commitment Permissions API", "HttpClient")
System_Ext(d_http_api_commitments_api, "Commitments API", "HttpClient")

Rel(c_employer_commitments, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_employer_commitments, d_http_api_approvals_api, "Calls the API of", "HttpClient")
Rel(c_employer_commitments, d_http_api_commitment_permissions_api, "Calls the API of", "HttpClient")
Rel(c_employer_commitments, d_http_api_commitments_api, "Calls the API of", "HttpClient")

@enduml
