@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_campaign, "Campaign") {
  Container(c_campaign_web, "Campaign", "Web Application")
}

SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
System_Ext(d_cloud_service_azure_key_vault, "Azure Key Vault", "Azure.Identity")
System_Ext(d_http_api_outer_api, "Outer API", "HttpClient")
SystemQueue_Ext(d_message_broker_azure_queue_storage, "Azure Queue Storage", "Azure Storage Queue")

Rel(c_campaign_web, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_campaign_web, d_cloud_service_azure_key_vault, "Uses", "Azure.Identity")
Rel(c_campaign_web, d_http_api_outer_api, "Calls the API of", "HttpClient")
Rel(c_campaign_web, d_message_broker_azure_queue_storage, "Publishes messages to and consumes messages from", "Azure Storage Queue")

@enduml
