@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_digital_certification_api, "Digital Certificates") {
  Container(c_digital_certificates, "Digital Certificates", "API")
}

SystemDb_Ext(d_database_digital_certificates_database, "Digital Certificates Database", "SqlServer")

Rel(c_digital_certificates, d_database_digital_certificates_database, "Reads from and writes to", "SqlServer")

@enduml
