@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_commitments, "Commitments") {
  Container(c_commitments, "Commitments", "API")
  Container(c_commitments_external_handlers, "Commitments External Handlers", "Background Job")
  Container(c_commitments_jobs, "Commitments Jobs", "Background Job")
  Container(c_commitments_message_handlers, "Commitments Message Handlers", "Background Job")
}

SystemDb_Ext(d_cache_cache_storage, "Cache Storage")
SystemDb_Ext(d_cache_redis, "Redis", "Redis")
System_Ext(d_cloud_service_authentication_service, "Authentication Service")
System_Ext(d_cloud_service_encoding_service, "Encoding Service")
SystemDb_Ext(d_database_provider_commitments, "Provider Commitments", "Entity Framework Core (ProviderCommitmentsDbContext)")
System_Ext(d_grpc_service_reservations_api, "Reservations API", "gRPC")
System_Ext(d_http_api_account, "Account", "HttpClient")
System_Ext(d_http_api_approvals_outer, "Approvals Outer")
System_Ext(d_http_api_levy_transfer_matching, "Levy Transfer Matching", "HttpClient")
System_Ext(d_http_api_provider_relationships, "Provider Relationships", "HttpClient")
System_Ext(d_http_api_reservations, "Reservations")
SystemQueue_Ext(d_message_broker_nservicebus, "NServiceBus", "NServiceBus")
SystemDb_Ext(d_object_storage_azure_blob_storage, "Azure Blob Storage", "Azure Blob Storage")

Rel(c_commitments, d_cache_cache_storage, "Caches data in")
Rel(c_commitments_jobs, d_cache_redis, "Caches data in", "Redis")
Rel(c_commitments, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_commitments, d_cloud_service_authentication_service, "Uses")
Rel(c_commitments, d_cloud_service_encoding_service, "Uses")
Rel(c_commitments_message_handlers, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core (ProviderCommitmentsDbContext)")
Rel(c_commitments, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_jobs, d_database_provider_commitments, "Reads from and writes to", "Entity Framework")
Rel(c_commitments_external_handlers, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments, d_grpc_service_reservations_api, "Calls the gRPC service of", "gRPC")
Rel(c_commitments_jobs, d_http_api_account, "Calls the API of", "HttpClient")
Rel(c_commitments_message_handlers, d_http_api_approvals_outer, "Calls the API of")
Rel(c_commitments, d_http_api_approvals_outer, "Calls the API of", "HttpClient")
Rel(c_commitments, d_http_api_levy_transfer_matching, "Calls the API of", "HttpClient")
Rel(c_commitments_jobs, d_http_api_provider_relationships, "Calls the API of", "HttpClient")
Rel(c_commitments_jobs, d_http_api_reservations, "Calls the API of")
Rel(c_commitments, d_http_api_reservations, "Calls the API of", "HttpClient")
Rel(c_commitments, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments_external_handlers, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_object_storage_azure_blob_storage, "Stores objects in", "Azure Blob Storage")

@enduml
