@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_commitments, "Commitments") {
  Container(c_commitments, "Commitments", "API")
  Container(c_commitments_2, "Commitments", "Component")
  Container(c_commitments_3, "Commitments", "Background Job")
  Container(c_commitments_externalhandlers, "Commitments ExternalHandlers", "Background Job")
  Container(c_commitments_jobs, "Commitments Jobs", "Background Job")
  Container(c_commitments_message_handlers, "Commitments Message Handlers", "Background Job")
}

SystemDb_Ext(d_cache_cache_storage, "Cache Storage")
SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "StackExchange.Redis")
System_Ext(d_cloud_service_encoding_service, "Encoding Service")
SystemDb_Ext(d_database_provider_commitments_database, "Provider Commitments Database", "Entity Framework Core")
System_Ext(d_http_api_account, "Account", "HttpClient")
System_Ext(d_http_api_approvals_outer, "Approvals Outer")
System_Ext(d_http_api_email_validation_service, "Email Validation Service")
System_Ext(d_http_api_employer_agreement, "Employer Agreement")
System_Ext(d_http_api_levy_transfer_matching, "Levy Transfer Matching", "HttpClient")
System_Ext(d_http_api_levy_transfer_matching_api, "Levy Transfer Matching API")
System_Ext(d_http_api_provider_commitments_base_url, "Provider Commitments Base URL")
System_Ext(d_http_api_provider_relationships, "Provider Relationships", "HttpClient")
System_Ext(d_http_api_reservations, "Reservations")
SystemQueue_Ext(d_message_broker_learner_data, "Learner Data", "NServiceBus")
SystemQueue_Ext(d_message_broker_learning_paused_events, "Learning Paused Events", "NServiceBus")
SystemQueue_Ext(d_message_broker_learning_resumed_events, "Learning Resumed Events", "NServiceBus")
SystemQueue_Ext(d_message_broker_microsoft_service_bus, "Microsoft Service Bus", "Azure.Messaging.ServiceBus")
SystemQueue_Ext(d_message_broker_nservicebus, "NServiceBus", "NServiceBus")
SystemDb_Ext(d_object_storage_azure_blob_storage, "Azure Blob Storage", "Azure.Storage.Blobs")

Rel(c_commitments, d_cache_cache_storage, "Caches data in")
Rel(c_commitments, d_cache_redis_cache, "Caches data in", "StackExchange.Redis")
Rel(c_commitments_message_handlers, d_cloud_service_encoding_service, "Uses")
Rel(c_commitments_jobs, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_2, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework")
Rel(c_commitments_message_handlers, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_3, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_externalhandlers, d_database_provider_commitments_database, "Reads from and writes to", "Entity Framework")
Rel(c_commitments_2, d_http_api_account, "Calls the API of", "HttpClient")
Rel(c_commitments_message_handlers, d_http_api_approvals_outer, "Calls the API of")
Rel(c_commitments_3, d_http_api_approvals_outer, "Calls the API of")
Rel(c_commitments, d_http_api_approvals_outer, "Calls the API of", "HttpClient")
Rel(c_commitments, d_http_api_email_validation_service, "Calls the API of")
Rel(c_commitments_3, d_http_api_employer_agreement, "Calls the API of")
Rel(c_commitments, d_http_api_levy_transfer_matching, "Calls the API of", "HttpClient")
Rel(c_commitments_3, d_http_api_levy_transfer_matching_api, "Calls the API of")
Rel(c_commitments, d_http_api_provider_commitments_base_url, "Calls the API of")
Rel(c_commitments_2, d_http_api_provider_relationships, "Calls the API of", "HttpClient")
Rel(c_commitments_3, d_http_api_provider_relationships, "Calls the API of")
Rel(c_commitments_jobs, d_http_api_reservations, "Calls the API of")
Rel(c_commitments, d_http_api_reservations, "Calls the API of", "HttpClient")
Rel(c_commitments, d_message_broker_learner_data, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_message_broker_learning_paused_events, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_message_broker_learning_resumed_events, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_message_broker_microsoft_service_bus, "Publishes messages to and consumes messages from", "Azure.Messaging.ServiceBus")
Rel(c_commitments, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments_externalhandlers, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments_jobs, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments_3, d_object_storage_azure_blob_storage, "Stores objects in", "Azure.Storage.Blobs")
Rel(c_commitments, d_object_storage_azure_blob_storage, "Stores objects in", "Azure.Storage.Blobs")

@enduml
