@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_commitments, "Commitments") {
  Container(c_commitments, "Commitments", "API")
  Container(c_commitments_2, "Commitments", "Component")
  Container(c_commitments_external_handlers, "Commitments External Handlers", "Background Job")
  Container(c_commitments_jobs, "Commitments Jobs", "Background Job")
  Container(c_commitments_messagehandlers, "Commitments MessageHandlers", "Background Job")
}

SystemDb_Ext(d_cache_cache_storage, "Cache Storage")
SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
System_Ext(d_cloud_service_mediator, "Mediator")
System_Ext(d_cloud_service_provider_commitments_configuration, "Provider Commitments Configuration")
SystemDb_Ext(d_database_provider_commitments, "Provider Commitments", "Entity Framework Core")
System_Ext(d_http_api_approvals_outer, "Approvals Outer", "HttpClient")
System_Ext(d_http_api_approvals_outer_api, "Approvals Outer Api")
System_Ext(d_http_api_email_validation_service, "Email Validation Service")
System_Ext(d_http_api_employer_accounts, "Employer Accounts", "HttpClient")
System_Ext(d_http_api_levy_transfer_matching, "Levy Transfer Matching", "HttpClient")
System_Ext(d_http_api_provider_relationships, "Provider Relationships", "HttpClient")
System_Ext(d_http_api_reservations, "Reservations")
SystemQueue_Ext(d_message_broker_nservicebus, "NServiceBus", "NServiceBus")
SystemQueue_Ext(d_message_broker_service_bus, "Service Bus")

Rel(c_commitments_2, d_cache_cache_storage, "Caches data in")
Rel(c_commitments, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_commitments_jobs, d_cloud_service_mediator, "Uses")
Rel(c_commitments, d_cloud_service_provider_commitments_configuration, "Uses")
Rel(c_commitments, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_jobs, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_external_handlers, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments_messagehandlers, d_database_provider_commitments, "Reads from and writes to", "Entity Framework")
Rel(c_commitments_2, d_database_provider_commitments, "Reads from and writes to", "Entity Framework Core")
Rel(c_commitments, d_http_api_approvals_outer, "Calls the API of", "HttpClient")
Rel(c_commitments_messagehandlers, d_http_api_approvals_outer_api, "Calls the API of")
Rel(c_commitments, d_http_api_email_validation_service, "Calls the API of")
Rel(c_commitments_jobs, d_http_api_employer_accounts, "Calls the API of", "HttpClient")
Rel(c_commitments, d_http_api_levy_transfer_matching, "Calls the API of", "HttpClient")
Rel(c_commitments_jobs, d_http_api_provider_relationships, "Calls the API of", "HttpClient")
Rel(c_commitments_jobs, d_http_api_reservations, "Calls the API of")
Rel(c_commitments, d_http_api_reservations, "Calls the API of", "HttpClient")
Rel(c_commitments_external_handlers, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_message_broker_nservicebus, "Publishes messages to and consumes messages from", "NServiceBus")
Rel(c_commitments, d_message_broker_service_bus, "Publishes messages to and consumes messages from")

@enduml
