@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_employer_accounts, "Employer Accounts") {
  Container(c_employer_accounts, "Employer Accounts", "Web Application")
  Container(c_employer_accounts_2, "Employer Accounts", "API")
  Container(c_employer_accounts_jobs, "Employer Accounts Jobs", "Background Job")
  Container(c_employer_accounts_messagehandlers, "Employer Accounts MessageHandlers", "Background Job")
}

SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
SystemDb_Ext(d_cache_redis_for_data_protection, "Redis for Data Protection", "StackExchange Redis")
SystemDb_Ext(d_database_employer_accounts_database, "Employer Accounts Database", "Entity Framework")
System_Ext(d_http_api_apprenticeship_levy, "Apprenticeship Levy", "HttpClient")
System_Ext(d_http_api_apprenticeship_levy_api, "Apprenticeship Levy API")
System_Ext(d_http_api_commitments_v2, "Commitments V2", "HttpClient")
System_Ext(d_http_api_commitments_v2_api, "Commitments V2 API")
System_Ext(d_http_api_content, "Content", "HttpClient")
System_Ext(d_http_api_content_api, "Content API")
System_Ext(d_http_api_employer_accounts_outer_api, "Employer Accounts Outer API")
System_Ext(d_http_api_token_service, "Token Service", "HttpClient")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "Azure Service Bus")

Rel(c_employer_accounts_2, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_employer_accounts_2, d_cache_redis_for_data_protection, "Caches data in", "StackExchange Redis")
Rel(c_employer_accounts, d_database_employer_accounts_database, "Reads from and writes to", "Entity Framework")
Rel(c_employer_accounts_2, d_database_employer_accounts_database, "Reads from and writes to", "Microsoft Entity Framework Core")
Rel(c_employer_accounts_2, d_http_api_apprenticeship_levy, "Calls the API of", "HttpClient")
Rel(c_employer_accounts, d_http_api_apprenticeship_levy_api, "Calls the API of")
Rel(c_employer_accounts_2, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employer_accounts, d_http_api_commitments_v2_api, "Calls the API of")
Rel(c_employer_accounts_2, d_http_api_content, "Calls the API of", "HttpClient")
Rel(c_employer_accounts, d_http_api_content_api, "Calls the API of")
Rel(c_employer_accounts, d_http_api_employer_accounts_outer_api, "Calls the API of")
Rel(c_employer_accounts_2, d_http_api_employer_accounts_outer_api, "Calls the API of", "HttpClient")
Rel(c_employer_accounts_2, d_http_api_token_service, "Calls the API of", "HttpClient")
Rel(c_employer_accounts_2, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")
Rel(c_employer_accounts_jobs, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")
Rel(c_employer_accounts_messagehandlers, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure Service Bus")

@enduml
