@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_employer_accounts, "Employer Accounts") {
  Container(c_employer_accounts, "Employer Accounts", "API")
  Container(c_employer_accounts_jobs, "Employer Accounts Jobs", "Background Job")
  Container(c_employer_accounts_messagehandlers, "Employer Accounts MessageHandlers", "Background Job")
  Container(c_employer_accounts_web, "Employer Accounts", "Web Application")
}

SystemDb_Ext(d_cache_data_protection_redis, "Data Protection Redis", "Redis (StackExchange)")
SystemDb_Ext(d_cache_redis, "Redis", "StackExchange.Redis")
SystemDb_Ext(d_database_employer_accounts_database, "Employer Accounts Database", "SQL Server")
System_Ext(d_http_api_apprenticeship_levy, "Apprenticeship Levy")
System_Ext(d_http_api_commitments_v2, "Commitments V2")
System_Ext(d_http_api_content, "Content")
System_Ext(d_http_api_content_api, "Content API", "HttpClient")
System_Ext(d_http_api_employer_accounts_outer_api, "Employer Accounts Outer API", "HttpClient")
SystemQueue_Ext(d_message_broker_azure_service_bus, "Azure Service Bus", "Azure.ServiceBus")
SystemQueue_Ext(d_message_broker_nservicebus_sql_server, "NServiceBus SQL Server", "NServiceBus.SQLServer")

Rel(c_employer_accounts, d_cache_data_protection_redis, "Caches data in", "Redis (StackExchange)")
Rel(c_employer_accounts, d_cache_redis, "Caches data in", "StackExchange.Redis")
Rel(c_employer_accounts_web, d_database_employer_accounts_database, "Reads from and writes to", "SQL Server")
Rel(c_employer_accounts, d_database_employer_accounts_database, "Reads from and writes to", "SQL Server")
Rel(c_employer_accounts_web, d_http_api_apprenticeship_levy, "Calls the API of")
Rel(c_employer_accounts, d_http_api_apprenticeship_levy, "Calls the API of", "HttpClient")
Rel(c_employer_accounts_web, d_http_api_commitments_v2, "Calls the API of")
Rel(c_employer_accounts, d_http_api_commitments_v2, "Calls the API of", "HttpClient")
Rel(c_employer_accounts_web, d_http_api_content, "Calls the API of")
Rel(c_employer_accounts, d_http_api_content_api, "Calls the API of", "HttpClient")
Rel(c_employer_accounts, d_http_api_employer_accounts_outer_api, "Calls the API of", "HttpClient")
Rel(c_employer_accounts, d_message_broker_azure_service_bus, "Publishes messages to and consumes messages from", "Azure.ServiceBus")
Rel(c_employer_accounts_jobs, d_message_broker_nservicebus_sql_server, "Publishes messages to and consumes messages from", "NServiceBus.SQLServer")
Rel(c_employer_accounts_messagehandlers, d_message_broker_nservicebus_sql_server, "Publishes messages to and consumes messages from", "NServiceBus.SQLServer")

@enduml
