@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_providerfeedback_web, "Provider Feedback") {
  Container(c_provider_feedback, "Provider Feedback", "Web Application")
}

SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
System_Ext(d_http_api_provider_feedback_outer, "Provider Feedback Outer", "HttpClient")

Rel(c_provider_feedback, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_provider_feedback, d_http_api_provider_feedback_outer, "Calls the API of", "HttpClient")

@enduml
