@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_WITH_LEGEND()

System_Boundary(sys_SkillsFundingAgency_das_reservations, "Reservations") {
  Container(c_reservations_web, "Reservations", "Web Application")
}

SystemDb_Ext(d_cache_redis_cache, "Redis Cache", "Redis")
System_Ext(d_http_api_reservations_api, "Reservations API", "HttpClient")

Rel(c_reservations_web, d_cache_redis_cache, "Caches data in", "Redis")
Rel(c_reservations_web, d_http_api_reservations_api, "Calls the API of", "HttpClient")

@enduml
